image: node:16

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            # Install AWS cli
            - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            - unzip awscliv2.zip
            - ./aws/install
            # Build and deploy frontend
            - cd frontend && npm install && npm run build-prod && cd -
            - aws s3 sync --delete public/ s3://ingatlanfigyelo
