version: "3.1"
services:
  web:
    image: rutkai/ingatlanfigyelo
    command: ["npm", "run", "start-web"]
    depends_on:
      - mongo
      - redis
    ports:
      - 3000:3000
    restart: unless-stopped
  polling:
    image: rutkai/ingatlanfigyelo
    command: ["npm", "run", "start-polling"]
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
  mongo:
    image: mongo:4.4
    volumes:
      - ./var/db/:/data/db
    restart: unless-stopped
  redis:
    image: redis:7
    restart: unless-stopped
