version: "3.1"
services:
  web:
    environment:
      NODE_ENV: production
    volumes:
      - ./config:/srv/config:ro
      - ./var:/srv/var
  polling:
    environment:
      NODE_ENV: production
    volumes:
      - ./config:/srv/config:ro
      - ./var:/srv/var
