version: "3.1"
services:
  web:
    environment:
      NODE_ENV: development
    volumes:
      - ./:/srv
      - ../public:/srv/public
  polling:
    environment:
      NODE_ENV: development
    volumes:
      - ./:/srv
  mongo:
    ports:
      - 27017:27017
  redis:
    ports:
      - 6379:6379
