version: "3.1"
services:
  web:
    environment:
      NODE_ENV: production
    volumes:
      - ./config:/srv/config:ro
  polling:
    environment:
      NODE_ENV: production
    volumes:
      - ./config:/srv/config:ro
