export enum EstateAttributes {
  DISTRICT = "district",
  CITY = "city",
  REGION = "region",
  BALCONY = "balcony",
  ELEVATOR = "elevator",
  FLOOR = "floor",
  HEATING = "heating",
  PRICE = "price",
  ROOMS = "rooms",
  HALF_ROOMS = "halfrooms",
  SIZE = "size",
  MATERIAL = "material",
  DESCRIPTION = "descriptionText",
  SQUARE_METER_PRICE = "squareMeterPrice",
  SOURCE = "source",
}
